---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.2
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[t3-kvm::default]
    attributes:
